package interfacce_principali;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author loren
 */
public class frmPrincipaleDipendente extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipaleDipendente
     */
    public frmPrincipaleDipendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDatiAnag = new javax.swing.JButton();
        btnGestMov = new javax.swing.JButton();
        btnGestConti = new javax.swing.JButton();
        btnGestCarte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDatiAnag.setText("gestione dati anagrafici");
        btnDatiAnag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatiAnagActionPerformed(evt);
            }
        });

        btnGestMov.setText("gestione movimenti");
        btnGestMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestMovActionPerformed(evt);
            }
        });

        btnGestConti.setText("gestione conti");
        btnGestConti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestContiActionPerformed(evt);
            }
        });

        btnGestCarte.setText("gestione carte");
        btnGestCarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestCarteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDatiAnag, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(btnGestCarte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestMov, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestConti, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatiAnag)
                    .addComponent(btnGestConti))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestCarte)
                    .addComponent(btnGestMov))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestContiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestContiActionPerformed
        // TODO add your handling code here:
        new interfacce_DipendenteBanca.frmGestioneConti().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestContiActionPerformed

    private void btnGestCarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestCarteActionPerformed
        // TODO add your handling code here: bennagay
        new interfacce_DipendenteBanca.frmGestioneCarte().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestCarteActionPerformed

    private void btnDatiAnagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatiAnagActionPerformed
        // TODO add your handling code here:
        new interfacce_DipendenteBanca.frmGestioneDatiAnagrafici().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDatiAnagActionPerformed

    private void btnGestMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestMovActionPerformed
        // TODO add your handling code here:
        new interfacce_DipendenteBanca.frmGestioneMovimenti().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaleDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaleDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaleDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaleDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipaleDipendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatiAnag;
    private javax.swing.JButton btnGestCarte;
    private javax.swing.JButton btnGestConti;
    private javax.swing.JButton btnGestMov;
    // End of variables declaration//GEN-END:variables
}
